// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TTSimg

#ifndef _TTSIMG_UI_H
#define _TTSIMG_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

#include "ui_img_manager.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern lv_img_dsc_t ui_img_01_png;   
void ui_img_01_png_load();
extern lv_img_dsc_t ui_img_02_png;   
void ui_img_02_png_load();
extern lv_img_dsc_t ui_img_03_png;   
void ui_img_03_png_load();
extern lv_img_dsc_t ui_img_04_png;   
void ui_img_04_png_load();
extern lv_img_dsc_t ui_img_05_png;   
void ui_img_05_png_load();
extern lv_img_dsc_t ui_img_06_png;   
void ui_img_06_png_load();
extern lv_img_dsc_t ui_img_07_png;   
void ui_img_07_png_load();
extern lv_img_dsc_t ui_img_08_png;   
void ui_img_08_png_load();
extern lv_img_dsc_t ui_img_09_png;   
void ui_img_09_png_load();
extern lv_img_dsc_t ui_img_10_png;   
void ui_img_10_png_load();


extern lv_img_dsc_t ui_img_1049104300;   
void ui_img_1049104300_load();

// FONTS
LV_FONT_DECLARE(ui_font_Font3);
LV_FONT_DECLARE(ui_font_Font4);
LV_FONT_DECLARE(ui_font_Font5);
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
