// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: animal

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_que;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_LabelA;
extern lv_obj_t * ui_labA;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_LabelB;
extern lv_obj_t * ui_LabB;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_LabelC;
extern lv_obj_t * ui_LabC;
extern void ui_event_btnans(lv_event_t * e);
extern lv_obj_t * ui_btnans;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

