// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: album

#include "ui.h"


// IMAGE DATA: assets/03.png
lv_img_dsc_t ui_img_03_png = {
    .header.always_zero = 0,
    .header.w = 578,
    .header.h = 339,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
};

void ui_img_03_png_load()
{
    ui_img_03_png.data = UI_LOAD_IMAGE("S:assets/ui_img_03_png.bin", 391884);
    ui_img_03_png.data_size = 391884;
}
