// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TTSimg

#include "ui.h"


// IMAGE DATA: assets/vid-na-3d-masinu_1_.png
lv_img_dsc_t ui_img_792570069 = {
    .header.always_zero = 0,
    .header.w = 578,
    .header.h = 339,
    .header.cf = LV_IMG_CF_TRUE_COLOR,
};

void ui_img_792570069_load()
{
    ui_img_792570069.data = UI_LOAD_IMAGE("S:assets/ui_img_792570069.bin", 391884);
    ui_img_792570069.data_size = 391884;
}
