// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: animal

#include "ui.h"


// IMAGE DATA: assets/icons8-question-mark-45.png
lv_img_dsc_t ui_img_81777710 = {
    .header.always_zero = 0,
    .header.w = 45,
    .header.h = 45,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_81777710_load()
{
    ui_img_81777710.data = UI_LOAD_IMAGE("S:assets/ui_img_81777710.bin", 6075);
    ui_img_81777710.data_size = 6075;
}
