// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TTSimg

#include "ui.h"


// IMAGE DATA: assets/08.png
lv_img_dsc_t ui_img_08_png = {
    .header.always_zero = 0,
    .header.w = 578,
    .header.h = 339,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_08_png_load()
{
    ui_img_08_png.data = UI_LOAD_IMAGE("S:assets/ui_img_08_png.bin", 587826);
    ui_img_08_png.data_size = 587826;
}
