// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TTSimg

#include "ui.h"


// IMAGE DATA: assets/icons8-next-55.png
lv_img_dsc_t ui_img_1049104300 = {
    .header.always_zero = 0,
    .header.w = 55,
    .header.h = 55,
    .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
};

void ui_img_1049104300_load()
{
    ui_img_1049104300.data = UI_LOAD_IMAGE("S:assets/ui_img_1049104300.bin", 9075);
    ui_img_1049104300.data_size = 9075;
}
