// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: TTSimg

#include "ui.h"
#include "ui_events.h"      // ← прототип apply_image_for_case
#include "builtin_texts.h"  // ← прототип builtin_text_get

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_btnsay = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Img = NULL;
lv_obj_t * ui_btnchg = NULL;
lv_obj_t * ui_arrow = NULL;
// event funtions
void ui_event_btnsay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_btn_say_pressed(e);
    }
}

void ui_event_btnchg(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        on_btn_change_pressed(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Screen1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Screen1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Screen1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnsay = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnsay, 150);
    lv_obj_set_height(ui_btnsay, 150);
    lv_obj_set_x(ui_btnsay, -379);
    lv_obj_set_y(ui_btnsay, 225);
    lv_obj_set_align(ui_btnsay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnsay, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_ON_FOCUS);    
    lv_obj_clear_flag(ui_btnsay, LV_OBJ_FLAG_SCROLLABLE);      
    lv_obj_set_style_radius(ui_btnsay, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnsay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnsay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_btnsay);
    lv_obj_set_width(ui_Label1, 89);   
    lv_obj_set_height(ui_Label1, 82);    
    lv_obj_set_x(ui_Label1, 26);
    lv_obj_set_y(ui_Label1, -13);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Learn    More");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Img = lv_img_create(ui_Screen1);
    lv_obj_set_width(ui_Img, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Img, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Img, 43);
    lv_obj_set_y(ui_Img, -49);
    lv_obj_set_align(ui_Img, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Img, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Img, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Img, lv_color_hex(0x282828), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Img, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Img, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Img, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnchg = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btnchg, 150);
    lv_obj_set_height(ui_btnchg, 150);
    lv_obj_set_x(ui_btnchg, 379);
    lv_obj_set_y(ui_btnchg, 225);
    lv_obj_set_align(ui_btnchg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnchg, LV_OBJ_FLAG_IGNORE_LAYOUT | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btnchg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_btnchg, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnchg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnchg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arrow = lv_img_create(ui_btnchg);
    lv_img_set_src(ui_arrow, &ui_img_1049104300);
    lv_obj_set_width(ui_arrow, LV_SIZE_CONTENT);   
    lv_obj_set_height(ui_arrow, LV_SIZE_CONTENT);    
    lv_obj_set_x(ui_arrow, -20);
    lv_obj_set_y(ui_arrow, -15);
    lv_obj_set_align(ui_arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_arrow, LV_OBJ_FLAG_ADV_HITTEST);     
    lv_obj_clear_flag(ui_arrow, LV_OBJ_FLAG_SCROLLABLE);      

    lv_obj_add_event_cb(ui_btnsay, ui_event_btnsay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnchg, ui_event_btnchg, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_btnsay = NULL;
    ui_Label1 = NULL;
    ui_Img = NULL;
    ui_btnchg = NULL;
    ui_arrow = NULL;

}
